FROM node:14.16.0-buster-slim@sha256:ffc15488e56d99dbc9b90d496aaf47901c6a940c077bc542f675ae351e769a12
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y wget  \
    && rm -rf /var/lib/apt/lists/* \
    && wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh \
    && chmod +x /usr/sbin/wait-for-it.sh

RUN npm i -g typeorm tsc

COPY package*.json ./

RUN npm ci

# Bundle app source
COPY . .

EXPOSE 80

RUN tsc

ENTRYPOINT [ "./entrypoint.sh"]
