version: "3.3"
services:
  redis:
    image: redis
    restart: unless-stopped
    hostname: redis
    ports:
      - "6379:6379"
  floor-api:
    build:
      context: .
      dockerfile: Dockerfile.amd
    environment:
      PORT: 80
      LOG_LEVEL: silly
    ports:
      - 80:80
