FROM node:14.16.0-buster-slim@sha256:ffc15488e56d99dbc9b90d496aaf47901c6a940c077bc542f675ae351e769a12
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y wget  \
    && rm -rf /var/lib/apt/lists/* \
    && wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh \
    && chmod +x /usr/sbin/wait-for-it.sh

WORKDIR /usr/src/app

RUN npm install -g npm@latest

RUN npm install -g typescript

COPY package*.json ./

RUN npm ci

# Bundle app source
COPY . .

EXPOSE 80

ENV NODE_ENV production

RUN tsc

RUN npm ci

ENTRYPOINT [ "./entrypoint.sh"]
